#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2025 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
prepare_service 10-mosquitto
SERVICE_NAME="mosquitto"

check_container_initialized
check_service_initialized init

if [ -n "${ADMIN_USER}" ] && [ -n "${ADMIN_PASS}" ]; then
    _mosquitto_admin_credentials="--username ${ADMIN_USER} --password ${ADMIN_PASS}"
fi
liftoff

print_start "Starting mosquitto $(mosquitto -h | head -n1 | awk '{print $3}')"
exec mosquitto \
                -c "${CONFIG_PATH}"/"${CONFIG_FILE}"
