services:

  mosquitto-app:
    image: nfrastack/mosquitto:latest
    container_name: mosquitto-app
    volumes:
      #- ./config:/config
      - ./data:/data
      - ./logs:/logs
    environment:
      - TIMEZONE=America/Vancouver

      - LISTEN_PORT=1833

      - LOG_LEVEL=all
      - LOG_TYPE=console

      - CREDENTIAL01_USER=mosquitto
      - CREDENTIAL01_PASS=secure

      - ENABLE_PERSISTENCE=FALSE
    networks:
      - services
    restart: always

networks:
  services:
    external: true
