name: "PUSH - Build on repository Push"
on:
  push:
    paths:
      - '**'
      - '!CHANGELOG.md'
      - '!/examples/*'
      - '!LICENSE'
      - '!README.md'
      - '!/zabbix_templates/*'
jobs:
  prepare:
    uses: nfrastack/gha/.github/workflows/artifacts-encrypt.yml@main
    secrets: inherit
  build:
    needs: prepare
    strategy:
      matrix:
        include:
          - distro: alpine
            distro_variant: 3.22
            latest: true
    uses: nfrastack/gha/.github/workflows/container-build_and_push.yml@main
    with:
      platforms: linux/amd64, linux/arm64
      base_image: ghcr.io/nfrastack/container-base
      distro: ${{ matrix.distro }}
      distro_variant: ${{ matrix.distro_variant }}
      include_distro_tag: false
      include_variant_tag: false
      latest: ${{ matrix.latest }}
    secrets: inherit
  cleanup:
    needs: [ build ]
    uses: nfrastack/gha/.github/workflows/artifacts-remove.yml@main
    secrets: inherit

